### ISSUE TITLE
Works only with opencv v2.4.9

### ISSUE THREAD

**Issue by dmitry** [D-Alex/ropencv#27]
I've tried to run examples with 2.4.8, 2.4.10 and 3.0.0 (trunk), and `match_keypoints.rb` example didn't worked for those versions. 2.4.8 and 3.0.0 related to https://github.com/D-Alex/ropencv/issues/26 and 2.4.10 isn't supported at all.

**Comment by D-Alex** [comment]
I fixed the example for opencv 3.0 on master (ropencv + rbind). Does that help or do you need the example to run on a specific version?
