### ISSUE TITLE
Open CV 3 support

### ISSUE THREAD

**Issue by wakiki** [D-Alex/ropencv#33]
Just wondering if the ropencv gem supports Open CV 3? There are KAZE and AKAZE in there which is useful as SURF/SIFT are patented.

From what I can see currently only OpenCV 2.4.11 is supported.

Am a bit new to this so apologies if I'm asking a stupid question!

Steve

**Comment by D-Alex** [comment]
OpenCV 3.0 Beta is supported.

Alex
