### ISSUE TITLE
Missing GaussianBlur and Canny

### ISSUE THREAD

**Issue by anthonator** [D-Alex/ropencv#35]
I can't access either `GaussianBlur` or `Canny`.

**Comment by anthonator** [comment]
Tried:

```ruby
OpenCV::Cv::GaussianBlur
```

```ruby
OpenCV::Cv::Canny
```

Also looked at everything defined on `OpenCV::Cv` using `OpenCV::Cv.constants` and did not see either class.

**Comment by D-Alex** [comment]
there are methods therefore you have to use the following notation:

    OpenCV::Cv.GaussianBlur(...)  #see opencv documentation for args
